name: Test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 6 * * *

jobs:
  Test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php:
          - 8.1
          - 8.2
          - 8.3
        phpunit:
          - 10
          - 11
        exclude:
          - php: 8.1
            phpunit: 11

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov

      - name: Filter PHPUnit version constraint
        run: 'sed -i ''s/\("phpunit\/phpunit" *: *\)\("\||\).*\(\^${{ matrix.phpunit }}\b[^|"]*\)\(|\|"\).*/\1"\3"/''
          composer.json'

      - name: Validate composer.json
        run: composer validate

      - name: Cache dependencies
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: php-${{ matrix.php }}-${{ matrix.phpunit }}

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Run test suite with coverage
        run: composer test -- --coverage-clover=build/logs/clover.xml

      - name: Upload test coverage
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
